services:
  db:
    image: postgres:16
    container_name: lab1_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: lab1_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-mydatabase}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-myuser}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "${APP_PORT:-8080}:8080"

volumes:
  db-data:
