name: Build and deploy JAR app to Azure Web App - Lab1Progr3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21 (Temurin) with Maven cache
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven (skip tests)
        run: ./mvnw -B -DskipTests package

      - name: Verify target content
        run: ls -lah target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar
          if-no-files-found: error
          retention-days: 3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ./artifact

      - name: List downloaded files
        run: ls -lah ./artifact

      - name: Resolve JAR path
        id: resolve-jar
        shell: bash
        run: |
          set -e
          JAR=$(ls -1 ./artifact/*.jar | grep -v 'original' | head -n 1 || true)
          if [ -z "$JAR" ]; then
            echo "No JAR found in ./artifact"; exit 1
          fi
          echo "jar=$JAR" >> $GITHUB_OUTPUT

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B8593E5EFCBA4C5BAEE843BB5EBEB34E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0C4FE6322832426BAEDBB305F5CB714E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_804EDAB18EA541EDA28C0530F5FB4BDB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Lab1Progr3'
          slot-name: 'Production'
          package: ${{ steps.resolve-jar.outputs.jar }}
